#ifndef CLASSIFICATION_H
#define CLASSIFICATION_H

enum Classification {

    OK,
    STATIC_SWITCH,
    STATIC_OVERPOWERED_TIME_PUSH,
    STATIC_MATCHED_POWER_TIME_PUSH,
    STATIC_MATCHED_POWER_POSITION_PUSH,
    POWER_MATCHED_TIME_PUSH,
    SCER
};

#endif
